[package]
name = "xrust-serialization-attribute-order-instability-issue-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
similar-asserts = "1.5.0"
xrust = { git = "https://github.com/ballsteve/xrust.git", branch = "dev" }
